apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "auth.fullname" . }}-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- include "auth.entryPoints" . | nindent 4 }}
  routes:
    - match: "Path(`/`)"
      kind: Rule
      middlewares:
        - name: {{ .Values.middlewares.rewriteToHealth.name }}
        - name: {{ .Values.middlewares.errorPages.name }}
        - name: {{ .Values.middlewares.authRequest.name }}
      services:
        {{- include "auth.service" . | nindent 8 }}

