apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: auth-route
  namespace: default
spec:
  entryPoints:
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - match: {{ .Values.ingressRoute.match }}
      kind: Rule
      middlewares:
        {{- range .Values.ingressRoute.middlewares }}
        - name: {{ . }}
        {{- end }}
      services:
        - name: {{ .Values.ingressRoute.service.name }}
          port: {{ .Values.ingressRoute.service.port }}
