apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middlewares.authRequest.name }}
  namespace: default
spec:
  forwardAuth:
    address: {{ .Values.middlewares.authRequest.address }}
    trustForwardHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middlewares.rewriteToHealth.name }}
  namespace: default
spec:
  replacePathRegex:
    regex: {{ .Values.middlewares.rewriteToHealth.regex }}
    replacement: {{ .Values.middlewares.rewriteToHealth.replacement }}