apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "auth.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.image.port }}