apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "error-pages.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "error-pages.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "error-pages.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "error-pages.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "error-pages.fullname" . }}-nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: error-content
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: error-content
          configMap:
            name: {{ include "error-pages.fullname" . }}-config
            items:
              {{- range $code, $message := .Values.errorMessages }}
              - key: {{ printf "%s.html" $code }}
                path: {{ printf "%s.html" $code }}
              {{- end }}
              - key: index.html
                path: index.html
        - name: nginx-config
          configMap:
            name: {{ include "error-pages.fullname" . }}-config
            items:
              - key: nginx.conf
                path: nginx.conf