replicaCount: 1

app:
  name: auth
  image:
    repository: auth
    tag: latest
    port: 5000

nameOverride: auth
fullnameOverride: auth

service:
  type: ClusterIP
  port: 5000

ingressRoute:
  entryPoints:
    - web
  middlewares:
    - auth-request
    - rewrite-to-health
  service:
    name: auth
    port: 5000

middlewares:
  authRequest:
    name: auth-request
    address: http://auth.default.svc.cluster.local:5000/auth
  rewriteToHealth:
    name: rewrite-to-health
    regex: ^/$
    replacement: /health
  errorPages:
    name: error-pages
    service:
      name: error-pages
      port: 80
    query: "/{status}.html"  # Dynamic query using status code
    statusCodes:
      - "400"
      - "401" 
      - "403"
      - "404"
      - "408"
      - "413"
      - "429"
      - "500"
      - "502"
      - "503"
      - "504"